In [2]:
import pandas as pd
from sklearn.decomposition import PCA

C:\Users\weezs\Anaconda3\envs\minjoo\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\weezs\Anaconda3\envs\minjoo\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\weezs\Anaconda3\envs\minjoo\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
df = pd.read_csv('data/iris.csv')
df[:5]

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [5]:
X = df.values[:,:-1]
print(X[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]]


In [6]:
X_reduced = PCA(3).fit_transform(X)

In [7]:
print(X_reduced[:5])
# 4-dims -> 3-dims

[[-2.68420713  0.32660731 -0.02151184]
 [-2.71539062 -0.16955685 -0.20352143]
 [-2.88981954 -0.13734561  0.02470924]
 [-2.7464372  -0.31112432  0.03767198]
 [-2.72859298  0.33392456  0.0962297 ]]


Normalization

In [8]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [9]:
df = pd.read_csv('data/glass.csv')
X = df.values[:,:-1]
y = df.values[:,-1]

normalizer = MinMaxScaler()
X_norm = normalizer.fit_transform(X)

In [10]:
X_norm[:10]

array([[0.2976295 , 0.30977444, 0.77951002, 0.25856698, 0.575     ,
        0.10305958, 0.31040892, 0.        , 0.        ],
       [0.23178227, 0.21503759, 0.78396437, 0.33021807, 0.55      ,
        0.09178744, 0.28810409, 0.        , 0.        ],
       [0.2976295 , 0.37293233, 0.77505568, 0.34890966, 0.50535714,
        0.09500805, 0.27881041, 0.        , 0.        ],
       [0.08077261, 0.5518797 , 0.38752784, 0.3894081 , 0.84642857,
        0.        , 0.20074349, 0.        , 0.        ],
       [1.        , 0.23609023, 0.        , 0.2211838 , 0.0625    ,
        0.01932367, 1.        , 0.        , 0.47058824],
       [0.23705004, 0.3037594 , 0.63474388, 0.35825545, 0.61785714,
        0.09178744, 0.31226766, 0.03492063, 0.43137255],
       [0.29148376, 0.43759398, 0.81291759, 0.11214953, 0.56964286,
        0.00966184, 0.32527881, 0.        , 0.        ],
       [0.31694469, 0.36240602, 0.6325167 , 0.30841121, 0.54285714,
        0.08856683, 0.33828996, 0.        , 0.        ],


In [11]:
normalizer = MinMaxScaler(feature_range=(0,100))
X_norm = normalizer.fit_transform(X)

print(normalizer.scale_)
print(normalizer.data_min_)
print(normalizer.data_max_)
print(normalizer.data_range_)

[4389.81562774   15.03759398   22.27171492   31.15264798   17.85714286
   16.10305958    9.2936803    31.74603175  196.07843137]
[ 1.51115 10.73     0.       0.29    69.81     0.       5.43     0.
  0.     ]
[ 1.53393 17.38     4.49     3.5     75.41     6.21    16.19     3.15
  0.51   ]
[ 0.02278  6.65     4.49     3.21     5.6      6.21    10.76     3.15
  0.51   ]


In [12]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [13]:
df = pd.read_csv('data/glass.csv')
X = df.values[:,:-1]
y = df.values[:,-1]

normalizer = StandardScaler()
X_norm = normalizer.fit_transform(X)
X_norm[:10]

array([[-1.43714541e-01, -7.58384063e-01,  5.66676959e-01,
        -6.52289486e-01,  4.90550986e-01,  2.19688551e-01,
        -1.31680092e-01, -3.52876828e-01, -5.86450902e-01],
       [-6.38803268e-01, -1.53168114e+00,  5.80575173e-01,
        -1.90536451e-01,  3.09376090e-01,  1.12106515e-01,
        -3.00715072e-01, -3.52876828e-01, -5.86450902e-01],
       [-1.43714541e-01, -2.42852679e-01,  5.52778744e-01,
        -7.00791379e-02, -1.41505092e-02,  1.42844239e-01,
        -3.71146313e-01, -3.52876828e-01, -5.86450902e-01],
       [-1.77420675e+00,  1.21781957e+00, -6.56365903e-01,
         1.90911708e-01,  2.45759271e+00, -7.63918639e-01,
        -9.62768741e-01, -3.52876828e-01, -5.86450902e-01],
       [ 5.13723188e+00, -1.35983734e+00, -1.86551055e+00,
        -8.93204112e-01, -3.22353438e+00, -5.79492291e-01,
         5.09431802e+00, -3.52876828e-01,  1.88241125e+00],
       [-5.99196170e-01, -8.07482290e-01,  1.14984993e-01,
        -9.85048123e-03,  8.01136522e-01,  1.121065

In [14]:
normalizer = StandardScaler()
X_norm = normalizer.fit_transform(X)

print(normalizer.scale_)
print(normalizer.mean_)
print(normalizer.var_)

[0.00302976 0.81469337 1.43903379 0.49810176 0.77273399 0.65066625
 1.41982447 0.49605617 0.09721077]
[1.51836542e+00 1.34078505e+01 2.68453271e+00 1.44490654e+00
 7.26509346e+01 4.97056075e-01 8.95696262e+00 1.75046729e-01
 5.70093458e-02]
[9.17944538e-06 6.63725286e-01 2.07081824e+00 2.48105365e-01
 5.97117818e-01 4.23366567e-01 2.01590152e+00 2.46071727e-01
 9.44993449e-03]


In [16]:
import numpy as np
df = pd.read_csv('data/glass.csv')
X = df.values[:,:-1].astype(np.float32)
df = pd.DataFrame(X)
X_norm = (df - df.mean()) / df.mad()

In [18]:
df.mean(), df.mad()

(0     1.518365
 1    13.407849
 2     2.684532
 3     1.444906
 4    72.650948
 5     0.497056
 6     8.956965
 7     0.175047
 8     0.057009
 dtype: float32, 0    0.002121
 1    0.598898
 2    1.209407
 3    0.359052
 4    0.555693
 5    0.294363
 6    0.918128
 7    0.292369
 8    0.077480
 dtype: float32)

In [19]:
X_norm

0         1         2         3         4         5         6  \
0   -0.205174 -1.031644  0.674271 -0.904900  0.682124  0.485604 -0.203637   
1   -0.912295 -2.083577  0.690808 -0.264325  0.430187  0.247802 -0.465039   
2   -0.205174 -0.330356  0.657734 -0.097218 -0.019702  0.315745 -0.573956   
3   -2.533958  1.656628 -0.780988  0.264846  3.417455 -1.688584 -1.488862   
4    7.337357 -1.849814 -2.219709 -1.239113 -4.482591 -1.280924  7.878026   
..        ...       ...       ...       ...       ...       ...       ...   
209 -1.067847  0.020289  0.591586 -0.626389  0.070281  0.315745 -0.693766   
210 -1.152703 -0.914764  0.690808  1.880209  0.016297  0.655462 -1.074976   
211 -1.053741  0.855156  0.690808 -0.542836  0.412188 -0.431632 -1.107651   
212 -0.695432 -1.232012  0.161623  0.738315  1.006044  0.791349 -0.454147   
213  0.072943  1.139011 -0.408905  0.599059  0.034283 -1.688584  0.395407   

            7         8  
0   -0.598718 -0.735792  
1   -0.598718 -0.735792  
2   -0.598718 -0.735792  
3   -0.598718 -0.735792  
4   -0.598718  2.361772  
..        ...       ...  
209 -0.598718 -0.735792  
210 -0.598718 -0.735792  
211 -0.598718  1.071120  
212 -0.598718 -0.735792  
213 -0.598718 -0.735792  

[214 rows x 9 columns]