In [18]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest, chi2
X, y = load_digits(return_X_y=True)
X.shape, y.shape

((1797, 64), (1797,))

In [20]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
X_new = SelectKBest(chi2, k=20).fit_transform(X, y)
X_new.shape

(1797, 20)

In [22]:
X_new

array([[ 1.,  0., 15., ...,  6.,  0.,  0.],
       [ 5.,  0.,  9., ...,  0., 10.,  0.],
       [12.,  0., 14., ...,  0., 16.,  9.],
       ...,
       [ 1.,  0.,  2., ...,  2.,  6.,  0.],
       [ 0.,  0., 15., ...,  5., 12.,  0.],
       [ 1.,  0.,  1., ...,  8., 12.,  1.]])

In [25]:
chi_scores = chi2(X,y)
chi_scores

(array([          nan,  811.90700411, 3501.28249552,  698.9252572 ,
         438.52969882, 3879.81925999, 3969.45823205, 1193.5608181 ,
          24.79521396, 2953.83108764, 2583.65198939,  388.24205944,
         824.69094853, 3676.48924765, 1983.5796061 ,  597.24198237,
           8.95886124, 1924.21690377, 2409.27140681, 3556.31594594,
        4871.94194551, 4782.19921618, 2155.17378998,  376.76583333,
           7.90090158, 2471.82418401, 4515.48149826, 2986.64314847,
        3724.09567634, 3208.64686641, 5138.07412439,   35.71270718,
                  nan, 5688.25079535, 5262.46646904, 3165.0605867 ,
        3231.63943369, 2532.99695611, 3288.81403655,           nan,
         142.85082873, 3863.85787901, 6416.0867248 , 5448.25154235,
        4079.73153383, 2134.02540236, 4486.34097862,  313.53898127,
          70.39927392,  449.72327313, 2801.97224468, 1527.54519627,
        1653.15892311, 3073.99803898, 5251.21748723,  683.88227339,
           9.15254237,  851.06791492, 3800.24731

__★ Chi-square method__

> * Chi-square를 통한 feature 선택방법은 x,y가 범주형 변수일때 사용가능하다.
> * 기대값이 5 이하인 경우에는 오류를 범할 수 있다. 
> * X가 연속형인 경우는? ANOVA for Feature selection을 써봐라?

* URL : https://towardsdatascience.com/chi-square-test-for-feature-selection-in-machine-learning-206b1f0b8223